### ISSUE TITLE
Clock Tick / Timing simulator

### ISSUE THREAD

**Issue by atharvalele** [atharvalele/ece585_final_project#5]
- A superloop?
- Event based?
- Think it out

**Comment by atharvalele** [comment]
- Superloop based working
- increment clock, do stuff
- Keeping track of both DRAM and CPU clock cycles

Minor adjustments might be needed as we go along

**Comment by doyleranpo** [comment]
- Time advancement of simulation time 
       - When the queue reaches that command to execute
       - When it is parsed 

Discuss when to advance time

**Comment by doyleranpo** [comment]
`cpu_clock_tick` variable needs to match the parsed line's request time when the request is should actually be put in the queue.

This can *also* indirectly accommodate the time jump that Prof was talking about.

So basically: after parsing the line we know what clock tick the request should be put in. Only put the request in when the clock matches the file req tick.

Another problem/question with this: when there are multiple requests with the same clock tick -- should they be put into the queue at the same time if there is space in the queue? Or should we take `n` CPU or DRAM clock cycles to do it.

**Comment by atharvalele** [comment]
Completed using superloop.

Requests scheduled at the same clock tick are serialized.
Flushing requests out of the DRAM controller queue is also serialized.
